name: Build with Local lpsolve

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: List lpsolve contents
      run: |
        # Show what's in the lpsolve directory
        ls -l lpsolve
    
    - name: Copy lpsolve libraries
      run: |
        # Copy .so files to a location where they can be found
        sudo cp lpsolve/*.so /usr/local/lib/ || true
        sudo ldconfig
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy cython setuptools wheel
        
        # Set library path to include project root
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}
        
        # Install the package
        pip install -e .
